apiVersion: types.kubefed.io/v1beta1
kind: FederatedDeployment
metadata:
  name: ml-job
spec:
  placement:
    clusters:
    - name: private-hybrid
  template:
    spec:
      selector:
        matchLabels:
          app: ml-job
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: ml-job
        spec:
          containers:
          - env:
            - name: AZURE_STORAGE_CONNECTION_STRING
              value: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://blob-storage:10000/devstoreaccount1;
            - name: EPOCHS
              value: "2"
            - name: JOB_NAME
              value: ml-job-2l1keocr37
            - name: ISTIO
              value: "true"
            image: smennig/ml-job:mnist
            imagePullPolicy: Always
            name: ml-job-2l1keocr37
            resources:
              limits:
                cpu: "1"
                memory: 1000Mi
              requests:
                cpu: 500m
                memory: 200Mi
